# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Amlan Limaye
email: amlan.limaye@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Data Science Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amlanlimaye.github.io" # the base hostname & protocol for your site
twitter_username: AmlanLimaye
github_username:  amlanlimaye

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-slate
gems:
  - jekyll-sitemap
